version: '3'
services:
  my_item_repository:
    image: danielev22/hgop:${GIT_COMMIT}
    ports:
    - target: 3000
      published: 3000
      protocol: tcp
      mode: host
    depends_on:
    - my_postgres_container
    environment:
      POSTGRES_DB: 'my_postgres_database'
      POSTGRES_USER: 'my_postgres_user'
      POSTGRES_PASSWORD: 'my_postgres_password'
      PORT: 3000
  my_postgres_container:
    image: postgres
    environment:
      POSTGRES_DB: 'my_postgres_database'
      POSTGRES_USER: 'my_postgres_user'
      POSTGRES_PASSWORD: 'my_postgres_password'