version: '3'
services:
  game-api:
    image: danielev22/hgop:${GIT_COMMIT}
    ports:
    - "3000:3000/tcp"
    depends_on:
    - game-database
    environment:
      POSTGRES_DB: 'pg_database'
      POSTGRES_USER: 'coreduo'
      POSTGRES_PASSWORD: 'intel2'
      POSTGRES_HOST: 'game-database'
      PORT: 3000
  game-database:
    image: postgres
    environment:
      POSTGRES_DB: 'pg_database'
      POSTGRES_USER: 'coreduo'
      POSTGRES_PASSWORD: 'intel2'
  game-ui:
    image: danielev22/hgop:ui2
    ports:
    - "4000:4000"
    environment:
      API_URL: danielev22/hgop:ui${GIT_COMMIT}
      PORT: 4000
    depends_on:
    - game-api