version: '3'
services:
  game-api:
    image: danielev22/hgop:API_${GIT_COMMIT}
    ports:
    - "3000:3000/tcp"
    depends_on:
    - game-database
    environment:
      POSTGRES_DB: 'pg_database'
      POSTGRES_USER: 'coreduo'
      POSTGRES_PASSWORD: 'intel2'
      POSTGRES_HOST: 'game-database'
      PORT: 3000
  game-database:
    image: postgres
    environment:
      POSTGRES_DB: 'pg_database'
      POSTGRES_USER: 'coreduo'
      POSTGRES_PASSWORD: 'intel2'
  game-client:
    image: danielev22/hgop:CLIENT_${GIT_COMMIT}
    ports:
    - "4000:4000"
    environment:
      API_URL: ${API_URL}
      PORT: 4000
    depends_on:
    - game-api
  datadog_container:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=1276353db216c9b47f502146bfd82c97
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_TAGS=env:${ENVIRONMENT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro