version: '3'
services:
  my_item_repository:
    image: danielev22/hgop:${GIT_COMMIT}
    ports:
    - "3000:3000/tcp"
    depends_on:
    - my_postgres_container
    environment:
      POSTGRES_DB: 'pg_database'
      POSTGRES_USER: 'coreduo'
      POSTGRES_PASSWORD: 'intel2'
      POSTGRES_HOST: 'my_postgres_container'
      PORT: 3000
  my_postgres_container:
    image: postgres
    environment:
      POSTGRES_DB: 'pg_database'
      POSTGRES_USER: 'coreduo'
      POSTGRES_PASSWORD: 'intel2'