version: '3'
services:
  game-api:
    image: danielev22/hgop:api
    ports:
    - "3000:3000/tcp"
    depends_on:
    - game-database
    environment:
      POSTGRES_DB: 'pg_database'
      POSTGRES_USER: 'coreduo'
      POSTGRES_PASSWORD: 'intel2'
      POSTGRES_HOST: 'game-database'
      PORT: 3000
  game-database:
    image: postgres
    environment:
      POSTGRES_DB: 'pg_database'
      POSTGRES_USER: 'coreduo'
      POSTGRES_PASSWORD: 'intel2'
  game-ui:
    image: danielev22/hgop:ui
    ports:
    - "4000:4000"
    environment:
      PORT: 4000
      API_URL: ${API_URL}
    depends_on:
    - game-api